////
 * Copyright (C) 2015 Eclipse Foundation, Inc. and others. 
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-FileType: SOURCE
 *
 * SPDX-FileCopyrightText: 2015 Eclipse Foundation, Inc.
 * SPDX-FileCopyrightText: 2015 Contributors to the Eclipse Foundation
 *
 * SPDX-License-Identifier: EPL-2.0
////

[[contact]]
== Getting Help

If you have any questions, or are unsure of your responsibilities as a xref:#roles-pl[project lead] or xref:roles-cm[committer], please contact your xref:#roles-pmc[Project Management Committee] (PMC), or the xref:#roles-emo[Eclipse Management Organization] (EMO) at {emoEmail}.

To request assistance with matters related to supported project infrastructure (e.g., Git repositories, mailing lists, builds), open a {helpdeskUrl}[Help Desk] issue.

To report vulnerabilities or report security issues contact {securityTeamEmail}. Please see xref:vulnerability[Managing and Reporting Vulnerabilities].

To ask questions about licensing or issues of a legal nature, contact {legalEmail}.

If you're not sure, contact {emoEmail}.