////
 * Copyright (C) 2024 Eclipse Foundation, Inc. and others. 
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-FileType: SOURCE
 *
 * SPDX-License-Identifier: EPL-2.0
////

:genai-evolving: pass:q,a[**This is a rapidly evolving area and this advice may change. This is not legal advice.**]

[#genai-faq]
= Frequently Asked Questions

[WARNING]
====
{genai-evolving}

This FAQ should not be regarded as legal advice. If you need legal advice, you must contact your own lawyer.
====

[qanda]
Can I add content that has been generated by an AI to an Eclipse open source project? ::

Yes.

What are my responsibilities when I accept a contribution that includes content that has been generated by an AI? ::

In addition to the Generative Artificial Intelligence Usage Guidelines for Eclipse Committers, the normal committer responsibilities, as described by the {committerGuidelinesUrl}[Eclipse Committer Due Diligence Guidelines] apply:
+
--
- Contributions must be vetted for correctness, and alignment with the project scope and goals;
- Contributions > 1K LOC must be reviewed by the IP Team; and
- If the contribution is known or is believed to contain any type of encryption software, the contribution must be approved by the appropriate PMC before being used.
--
+
If you are concerned that content may have been copied, is substantially similar to someone else’s content, or that a contributor is otherwise not operating in good faith, contact your PMC or the EMO for help and advice.

Am I required to accept contributions that have been generated by an AI? ::

No. As a committer you bear responsibility to ensure that the contributions that you receive are technically correct, align with project scope and goals, don’t include obvious vulnerabilities, and have been vetted via the xref:ip[IP Due Diligence Process]. As a committer you should not accept contributions, human- or AI-generated, that you don’t understand or are not willing or able to support.

How do I disclose that content has been co-authored by an AI? ::

{genai-evolving}
+
Our answer to this question is based on the following:
+
--
- AI-generated content is likely not copyrightable under current law in the EU and U.S. nor licenseable;
- Human modifications and curations may restore copyrightability to specific parts;
- Moving content into your project (curation) may be a copyrightable act;
- The https://creativecommons.org/public-domain/cc0/[CC0] "No Rights Reserved" (SPDX: `CC0-1.0`) dedication is widely used to designate content that is in the public domain; and
- Using `Assisted-by` tags is emerging as a de facto standard for capturing the identity of an AI assistant in a machine-readable format.
--
+
For files that are largely or entirely generated by an AI, add a standard copyright header expressing the project licence along with an AI disclosure.
+
For example, a project that uses the Eclipse Public License could use this template:
+
[%nowrap]
----
Copyright (c) 2026 Real H. Uman <1>

This program and the accompanying materials are made available under <2>
the terms of the Eclipse Public License 2.0 which accompanies this 
distribution, and is available at https://www.eclipse.org/legal/epl-2.0/

AI Disclosure: This file was largely AI-generated. The AI-generated <3>
portions are made available under CC0-1.0 and not subject to the 
project's licence. The human contributor has reviewed and verified 
that the code is correct.

SPDX-License-Identifier: EPL-2.0 and CC0-1.0 <4>
Assisted-by: Google gemini-2.5-pro (rev-1) <5>
----
<1> See xref:ip-copyright-headers[Copyright Headers].
<2> The project licence.
<3> "No rights reserved" dedication.
<4> SPDX expression that combines project licence and dedication (in an SPDX identifier expression, `and` means that the adopter must accept the terms of both sides of the expression).
<5> Identity of the AI assistant.
+
And in your commit message:
+
[%nowrap]
----
commit d6cf52411377a039fc2906378711091a26e932cb
Author: Real H. Uman <real@human.com> <1>
Date:   Wed May 29 16:17:36 2013 +0200

    Hide unwanted action bar items

    This change hides unwanted 'Link with Editor' and
    'Customize View...' items from the local toolbar
    and the view menu.

    Assisted-by: GitHub Copilot (GPT-4o-2024-08-06) <2>
----
<1> The responsible _human's_ credentials.
<2> Identity of the AI assistant

How do I identify the AI? ::

{genai-evolving}
+
There is no current standard for identifying the AI; this area is evolving, but a de facto standard is seems to be gaining momentum:
+
[%nowrap]
----
Assisted-by: [Provider] [Model-Family] ([Version/ID])
----
+
Examples:
+
[%nowrap]
----
Assisted-by: Google gemini-2.5-pro (rev-1)
Assisted-by: GitHub Copilot (GPT-4o-2024-08-06)
----
+
If providing all of this information is especially onerous or impossible, specify as much of it as you can.

Do I have to disclose the use of AI in all cases? ::

{genai-evolving}
+
This is a difficult question to answer. A disclosure is likely not required when an AI generates rote or simple boilerplate content that you then modify and supplement with more creative behaviour. A disclosure is likely not required for a spelling correction or the addition of a for loop, for example.
+
A simple rule of thumb is this: if you would give a human credit for the contribution, you should likely provide an AI disclosure. 

Can we create an account/bot that has the ability to push AI-generated content directly into a project repository without human intervention? ::

No. A human must review and approve every commit before it is merged into an Eclipse project repository, even when using agentic tools.

[[genai-plugins]]Can we install a GitHub extension that enables AI features? ::

Yes, but with some considerations. 
+
As a committer, you are responsible for ensuring that all content added to the repository, especially content that is generated via automation, is vetted for technical correctness, reviewed for security issues, is properly vetted via the IP Due Diligence Process, and is correctly attributed.
+
GitHub extensions that enable AI features tend to require privileges that allow them to write to the repository. To the extent possible, you must discourage the extension from exercising these privileges (pull requests that must be merged by a human are okay, direct pushes are not).
+
It’s also important that adding an extension doesn't limit opportunities for community engagement with the project. Before considering the use of an extension, consider the following questions:
+
--
- Does adding the extension unfairly benefit some committers and not others?
- Does adding the extension introduce a barrier for entry that might prevent others from contributing to the project?
--
+
Request installation of an extension by opening a {helpdeskUrl}[help desk] issue.
